inputs: [
    'inputs//nn-trains//small.csv',
    'inputs//nn-trains//small-ch04.csv'
]
subtitles: [
    'Small Map: Drones Battery Alert: 0.2',
    'Small Map: Drones Battery Alert: 0.4'
]
y: [
    'Survived Drone Rate',
    'Damage Rate',
]
x: 'Trains'
colors: [
    'blue',
    'orange'
]
lineStyles: [
    'solid',
    'solid',
]
type: 'line'
filename: 'trains-small-ch04'
size: [8,6]
title: 'Survived Drones vs Damage in 4 Neural Network Training'
